// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ca

import (
	"crypto/ed25519"
	"crypto/x509"
	"sg-emulator/internal/crypto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCertificateAuthority creates a new instance of MockCertificateAuthority. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateAuthority(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateAuthority {
	mock := &MockCertificateAuthority{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCertificateAuthority is an autogenerated mock type for the CertificateAuthority type
type MockCertificateAuthority struct {
	mock.Mock
}

type MockCertificateAuthority_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateAuthority) EXPECT() *MockCertificateAuthority_Expecter {
	return &MockCertificateAuthority_Expecter{mock: &_m.Mock}
}

// Certificate provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) Certificate() *x509.Certificate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Certificate")
	}

	var r0 *x509.Certificate
	if returnFunc, ok := ret.Get(0).(func() *x509.Certificate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	return r0
}

// MockCertificateAuthority_Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Certificate'
type MockCertificateAuthority_Certificate_Call struct {
	*mock.Call
}

// Certificate is a helper method to define mock.On call
func (_e *MockCertificateAuthority_Expecter) Certificate() *MockCertificateAuthority_Certificate_Call {
	return &MockCertificateAuthority_Certificate_Call{Call: _e.mock.On("Certificate")}
}

func (_c *MockCertificateAuthority_Certificate_Call) Run(run func()) *MockCertificateAuthority_Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertificateAuthority_Certificate_Call) Return(certificate *x509.Certificate) *MockCertificateAuthority_Certificate_Call {
	_c.Call.Return(certificate)
	return _c
}

func (_c *MockCertificateAuthority_Certificate_Call) RunAndReturn(run func() *x509.Certificate) *MockCertificateAuthority_Certificate_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatePEM provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) CertificatePEM() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatePEM")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCertificateAuthority_CertificatePEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatePEM'
type MockCertificateAuthority_CertificatePEM_Call struct {
	*mock.Call
}

// CertificatePEM is a helper method to define mock.On call
func (_e *MockCertificateAuthority_Expecter) CertificatePEM() *MockCertificateAuthority_CertificatePEM_Call {
	return &MockCertificateAuthority_CertificatePEM_Call{Call: _e.mock.On("CertificatePEM")}
}

func (_c *MockCertificateAuthority_CertificatePEM_Call) Run(run func()) *MockCertificateAuthority_CertificatePEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertificateAuthority_CertificatePEM_Call) Return(s string) *MockCertificateAuthority_CertificatePEM_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCertificateAuthority_CertificatePEM_Call) RunAndReturn(run func() string) *MockCertificateAuthority_CertificatePEM_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccountCredentials provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) CreateAccountCredentials() (*crypto.KeyPair, *x509.Certificate, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountCredentials")
	}

	var r0 *crypto.KeyPair
	var r1 *x509.Certificate
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func() (*crypto.KeyPair, *x509.Certificate, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *crypto.KeyPair); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.KeyPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *x509.Certificate); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() string); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func() error); ok {
		r3 = returnFunc()
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockCertificateAuthority_CreateAccountCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccountCredentials'
type MockCertificateAuthority_CreateAccountCredentials_Call struct {
	*mock.Call
}

// CreateAccountCredentials is a helper method to define mock.On call
func (_e *MockCertificateAuthority_Expecter) CreateAccountCredentials() *MockCertificateAuthority_CreateAccountCredentials_Call {
	return &MockCertificateAuthority_CreateAccountCredentials_Call{Call: _e.mock.On("CreateAccountCredentials")}
}

func (_c *MockCertificateAuthority_CreateAccountCredentials_Call) Run(run func()) *MockCertificateAuthority_CreateAccountCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertificateAuthority_CreateAccountCredentials_Call) Return(keyPair *crypto.KeyPair, certificate *x509.Certificate, s string, err error) *MockCertificateAuthority_CreateAccountCredentials_Call {
	_c.Call.Return(keyPair, certificate, s, err)
	return _c
}

func (_c *MockCertificateAuthority_CreateAccountCredentials_Call) RunAndReturn(run func() (*crypto.KeyPair, *x509.Certificate, string, error)) *MockCertificateAuthority_CreateAccountCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountCertificatePEM provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) GetAccountCertificatePEM(accountID string) (string, error) {
	ret := _mock.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountCertificatePEM")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(accountID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertificateAuthority_GetAccountCertificatePEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountCertificatePEM'
type MockCertificateAuthority_GetAccountCertificatePEM_Call struct {
	*mock.Call
}

// GetAccountCertificatePEM is a helper method to define mock.On call
//   - accountID string
func (_e *MockCertificateAuthority_Expecter) GetAccountCertificatePEM(accountID interface{}) *MockCertificateAuthority_GetAccountCertificatePEM_Call {
	return &MockCertificateAuthority_GetAccountCertificatePEM_Call{Call: _e.mock.On("GetAccountCertificatePEM", accountID)}
}

func (_c *MockCertificateAuthority_GetAccountCertificatePEM_Call) Run(run func(accountID string)) *MockCertificateAuthority_GetAccountCertificatePEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCertificateAuthority_GetAccountCertificatePEM_Call) Return(s string, err error) *MockCertificateAuthority_GetAccountCertificatePEM_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCertificateAuthority_GetAccountCertificatePEM_Call) RunAndReturn(run func(accountID string) (string, error)) *MockCertificateAuthority_GetAccountCertificatePEM_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountPrivateKeyPEM provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) GetAccountPrivateKeyPEM(accountID string) (string, error) {
	ret := _mock.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountPrivateKeyPEM")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(accountID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertificateAuthority_GetAccountPrivateKeyPEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountPrivateKeyPEM'
type MockCertificateAuthority_GetAccountPrivateKeyPEM_Call struct {
	*mock.Call
}

// GetAccountPrivateKeyPEM is a helper method to define mock.On call
//   - accountID string
func (_e *MockCertificateAuthority_Expecter) GetAccountPrivateKeyPEM(accountID interface{}) *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call {
	return &MockCertificateAuthority_GetAccountPrivateKeyPEM_Call{Call: _e.mock.On("GetAccountPrivateKeyPEM", accountID)}
}

func (_c *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call) Run(run func(accountID string)) *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call) Return(s string, err error) *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call) RunAndReturn(run func(accountID string) (string, error)) *MockCertificateAuthority_GetAccountPrivateKeyPEM_Call {
	_c.Call.Return(run)
	return _c
}

// IssueCertificate provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) IssueCertificate(accountID string, pubKey ed25519.PublicKey) (*x509.Certificate, error) {
	ret := _mock.Called(accountID, pubKey)

	if len(ret) == 0 {
		panic("no return value specified for IssueCertificate")
	}

	var r0 *x509.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ed25519.PublicKey) (*x509.Certificate, error)); ok {
		return returnFunc(accountID, pubKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ed25519.PublicKey) *x509.Certificate); ok {
		r0 = returnFunc(accountID, pubKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ed25519.PublicKey) error); ok {
		r1 = returnFunc(accountID, pubKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertificateAuthority_IssueCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCertificate'
type MockCertificateAuthority_IssueCertificate_Call struct {
	*mock.Call
}

// IssueCertificate is a helper method to define mock.On call
//   - accountID string
//   - pubKey ed25519.PublicKey
func (_e *MockCertificateAuthority_Expecter) IssueCertificate(accountID interface{}, pubKey interface{}) *MockCertificateAuthority_IssueCertificate_Call {
	return &MockCertificateAuthority_IssueCertificate_Call{Call: _e.mock.On("IssueCertificate", accountID, pubKey)}
}

func (_c *MockCertificateAuthority_IssueCertificate_Call) Run(run func(accountID string, pubKey ed25519.PublicKey)) *MockCertificateAuthority_IssueCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 ed25519.PublicKey
		if args[1] != nil {
			arg1 = args[1].(ed25519.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCertificateAuthority_IssueCertificate_Call) Return(certificate *x509.Certificate, err error) *MockCertificateAuthority_IssueCertificate_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *MockCertificateAuthority_IssueCertificate_Call) RunAndReturn(run func(accountID string, pubKey ed25519.PublicKey) (*x509.Certificate, error)) *MockCertificateAuthority_IssueCertificate_Call {
	_c.Call.Return(run)
	return _c
}


// PrivateKey provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) PrivateKey() ed25519.PrivateKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrivateKey")
	}

	var r0 ed25519.PrivateKey
	if returnFunc, ok := ret.Get(0).(func() ed25519.PrivateKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PrivateKey)
		}
	}
	return r0
}

// MockCertificateAuthority_PrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrivateKey'
type MockCertificateAuthority_PrivateKey_Call struct {
	*mock.Call
}

// PrivateKey is a helper method to define mock.On call
func (_e *MockCertificateAuthority_Expecter) PrivateKey() *MockCertificateAuthority_PrivateKey_Call {
	return &MockCertificateAuthority_PrivateKey_Call{Call: _e.mock.On("PrivateKey")}
}

func (_c *MockCertificateAuthority_PrivateKey_Call) Run(run func()) *MockCertificateAuthority_PrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertificateAuthority_PrivateKey_Call) Return(privateKey ed25519.PrivateKey) *MockCertificateAuthority_PrivateKey_Call {
	_c.Call.Return(privateKey)
	return _c
}

func (_c *MockCertificateAuthority_PrivateKey_Call) RunAndReturn(run func() ed25519.PrivateKey) *MockCertificateAuthority_PrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// PublicKey provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) PublicKey() ed25519.PublicKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PublicKey")
	}

	var r0 ed25519.PublicKey
	if returnFunc, ok := ret.Get(0).(func() ed25519.PublicKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PublicKey)
		}
	}
	return r0
}

// MockCertificateAuthority_PublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKey'
type MockCertificateAuthority_PublicKey_Call struct {
	*mock.Call
}

// PublicKey is a helper method to define mock.On call
func (_e *MockCertificateAuthority_Expecter) PublicKey() *MockCertificateAuthority_PublicKey_Call {
	return &MockCertificateAuthority_PublicKey_Call{Call: _e.mock.On("PublicKey")}
}

func (_c *MockCertificateAuthority_PublicKey_Call) Run(run func()) *MockCertificateAuthority_PublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertificateAuthority_PublicKey_Call) Return(publicKey ed25519.PublicKey) *MockCertificateAuthority_PublicKey_Call {
	_c.Call.Return(publicKey)
	return _c
}

func (_c *MockCertificateAuthority_PublicKey_Call) RunAndReturn(run func() ed25519.PublicKey) *MockCertificateAuthority_PublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCertificate provides a mock function for the type MockCertificateAuthority
func (_mock *MockCertificateAuthority) VerifyCertificate(cert *x509.Certificate) error {
	ret := _mock.Called(cert)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCertificate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*x509.Certificate) error); ok {
		r0 = returnFunc(cert)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCertificateAuthority_VerifyCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCertificate'
type MockCertificateAuthority_VerifyCertificate_Call struct {
	*mock.Call
}

// VerifyCertificate is a helper method to define mock.On call
//   - cert *x509.Certificate
func (_e *MockCertificateAuthority_Expecter) VerifyCertificate(cert interface{}) *MockCertificateAuthority_VerifyCertificate_Call {
	return &MockCertificateAuthority_VerifyCertificate_Call{Call: _e.mock.On("VerifyCertificate", cert)}
}

func (_c *MockCertificateAuthority_VerifyCertificate_Call) Run(run func(cert *x509.Certificate)) *MockCertificateAuthority_VerifyCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *x509.Certificate
		if args[0] != nil {
			arg0 = args[0].(*x509.Certificate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCertificateAuthority_VerifyCertificate_Call) Return(err error) *MockCertificateAuthority_VerifyCertificate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCertificateAuthority_VerifyCertificate_Call) RunAndReturn(run func(cert *x509.Certificate) error) *MockCertificateAuthority_VerifyCertificate_Call {
	_c.Call.Return(run)
	return _c
}
